### PR TITLE
[ConnectorV2] Support private key to connect in the box

### PR DESCRIPTION
**Pull request by pedroandrade**
# Description

- using a new field to grab the private key in memory and pass to the proxy instead of the upstream identity file

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by btoonk** [comment]
Is using ConnectorLocalData the right thing?

**Comment by pedroandrade** [comment]
@btoonk nops, but the proxy's config builder depends on that today, I'm gonna refactor it to not use the connectorLocalData at all, that's a thing from the connector v1

**Comment by btoonk** [comment]
We should also check if input is a variable that points to something locally.
ie. https://github.com/borderzero/border0-cli/tree/main/lib/varsource

**Comment by pedroandrade** [comment]
@btoonk sure!, this variable thing I'm gonna do in next PR

**Review by btoonk — APPROVED** [review]

**Pull request merged**
